swagger: "2.0"
info:
  title: "Documentación de Ejercicios"
  description: "Documentación de ejercicios para coordinadora."
  version: "1.0.0"
paths:
  /calcular_puntuacion_matriz:
    post:
      summary: "Calcula la puntuación de una matriz"
      description: "Calcula la puntuación total basada en una matriz de números según ciertas reglas."
      parameters:
        - in: body
          name: matriz
          description: "Matriz de números para calcular la puntuación"
          required: true
          schema:
            type: array
            items:
              type: integer
      responses:
        200:
          description: "Puntuación calculada exitosamente"
          schema:
            type: integer
