swagger: "2.0"
info:
  title: "Documentaci칩n de Ejercicios"
  description: "Documentaci칩n de ejercicios para coordinadora."
  version: "1.0.0"
paths:
  /calcular_tribonacci_secuencia:
    post:
      summary: "Genera la secuencia Tribonacci"
      description: "Genera la secuencia Tribonacci basada en una secuencia inicial v치lida de Fibonacci."
      parameters:
        - in: body
          name: secuencia_inicial
          description: "Secuencia inicial v치lida de Fibonacci"
          required: true
          schema:
            type: array
            items:
              type: integer
      responses:
        200:
          description: "Secuencia Tribonacci generada exitosamente"
          schema:
            type: array
            items:
              type: integer

